language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: multimedia-database
  on: master
  skip_cleanup: true
  api_key:
    secure: kCWWgatxdLlsaGS8z2PeDuZrN4XHcYPlmzGPVzlqaOMjE8kOW5uj8PdhXRFX0c1cp5cF5tM4D2fGVIKlfk8kOytgEQHKsCVrrVXCbZOnKvtVsMjyX6Y+7R4S2Mx/ltPVSpp/w1cr3BahgVMi0ShygJgyMQKb7F3gLXNZdWOLnweEqyOp36Hrs38Zqbd1187TpkU1K9fpayO8wbCtrotUIaMyIjuWcM9IkWKLjZwcAzCbaW9Ldf3a8qrHS/Ftpp5gtt3ZSNRyiuHdFWodz+hvC9JjuXwvux3ushekYqov5sJJeYNW9XQhKW75Z+TVbFdFdnuuqF41rAvi4aV0Gw1OXA9EPAcTvCduG4FXew8OL7lV5W9NOpBiNQ/GbWb3WZazSd+5k57fzoXk7NBVERAr6Il0L8OEKvRMj3bGYelF1cBMGhcheytq9ebwEHep3mzOaTGFUXNi6hgzUyJ75fCeus3wkSo0Kr28gr05Ga3p4hqJMGX813H0UWCWjy5GpaoB2vq6cnxG0hPEdV3dvRO+pBZv68KMjPIy5T8pGJpe8NoMtADRn0pSpRhYYjMt/1wfy/uwdm46iluS7k56OWzVp+DMtwDa2dfYPSIVVvSDpDGjqIEw38ufRLs2tGiga9f0F2RyKRAWsiLm4iSXae20erXXoGnXzTN19tq9+uY2ziM=
